name: Create new Release

on:
  workflow_dispatch:
    inputs:
      boomerang-version:
        description: Version of https://github.com/akamai/boomerang for which an SBOM should be built and released. Needs to match the version's tag.
        type: string
        required: true

jobs:
  build-and-release:
    runs-on: ubuntu-20.04
    steps:
      - name: debug
        run: ${{ format(echo {0}, inputs.boomerang-version) }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'akamai/boomerang'
          ref: 1.737.0
      - name: Build plugin
        run: |
          npm install grunt
          grunt clean build
      - name: Prepare BOM generation
        run: mkdir boomerang-boms
      - name: Generate XML BOM
        uses: CycloneDX/gh-node-module-generatebom@master
        with:
          output: ./boomerang-boms/boomerang-bom.xml
      - name: Generate JSON BOM
        uses: CycloneDX/gh-node-module-generatebom@master
        with:
          output: ./boomerang-boms/boomerang-bom.json
          json: true
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: test
          files: boomerang-boms/*
